### ISSUE TITLE
Feature: Adding support for Jikan API with retrofit

### ISSUE THREAD

**Issue by Horizon733** [Horizon733/Anime-app#4]
Below are some points to be considered before starting work on API integration
-  Make use of MVVM
- For reference, you can have a look at [Codelabs](https://codelabs.developers.google.com/) for MVVM tutorials
- For Jikan click [here](https://rapidapi.com/theapiguy/api/jikan1/)

**Comment by Hiten24** [comment]
Hey @Horizon733 can i work on this

**Comment by Horizon733** [comment]
> Hey @Horizon733 can i work on this

sure
